[package]
name = "crank"
version = "0.1.0"
authors = ["Rob Tsuk <robtsuk@google.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
dirs = "2.0.2"
Inflector = "0.11.4"
structopt = "0.3.14"
